baseURL = "https://valeriagommez.github.io/CAN-BON/"
defaultContentLanguage = "en"

[languages]
  [languages.en]
    languageName = "English"
    contentDir = "content/english"
    weight = 1
  [languages.fr]
    languageName = "Français"
    contentDir = "content/french"
    weight = 2

[markup.goldmark.renderer]
  unsafe = true