baseURL = '/'
locale = 'en-us'
title = 'CAN BON'

# allows html in the yaml file to be rendered
[markup.goldmark.renderer]
unsafe = true

# handling languages
defaultContentLanguage = "en"
[languages]
  [languages.en]
    params = "English"
    contentDir = "content/english"
    weight = 1
  [languages.fr]
    params = "Français"
    contentDir = "content/french"
    weight = 2